# Generated by Django 5.0 on 2024-04-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dry_skin', models.BooleanField(default=False)),
                ('oily_t_zone', models.BooleanField(default=False)),
                ('large_pores', models.BooleanField(default=False)),
                ('cold_feel_tight', models.BooleanField(default=False)),
                ('cold_feel_normal', models.BooleanField(default=False)),
                ('cream_absorption_fast', models.BooleanField(default=False)),
                ('cream_absorption_slow', models.BooleanField(default=False)),
                ('acne_no', models.BooleanField(default=False)),
                ('acne_few', models.BooleanField(default=False)),
                ('acne_many', models.BooleanField(default=False)),
                ('acne_lot', models.BooleanField(default=False)),
                ('irritated_skin', models.BooleanField(default=False)),
            ],
        ),
    ]
