# Generated by Django 5.0 on 2024-05-14 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineSkinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkinCareApp.skintype')),
            ],
        ),
        migrations.CreateModel(
            name='SkincareRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skin_types', models.ManyToManyField(through='SkinCareApp.RoutineSkinType', to='SkinCareApp.skintype')),
            ],
        ),
        migrations.CreateModel(
            name='SkincareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('product_url', models.URLField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='SkinCareApp.skincareroutine')),
            ],
        ),
        migrations.AddField(
            model_name='routineskintype',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkinCareApp.skincareroutine'),
        ),
    ]
