# Generated by Django 5.0 on 2024-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCareApp', '0003_alter_skincareproduct_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincareproduct',
            name='description_product',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
