# Generated by Django 5.0 on 2024-05-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCareApp', '0005_skintypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkinTypes',
            new_name='AboutSkinTypes',
        ),
    ]
